// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;





class Product
{
    public int ProductID;
    public string ProductName;
    public int ProductQuantity;
    public double Price;

}
class InventoryManagement
{
    public Dictionary<int, Product> Inventory = new Dictionary<int, Product>();
    public void add(int productID, Product product)
    {
        Inventory.Add(productID, product);
    }
    public void update(int productID)
    {
        Product temp = Inventory.GetValueOrDefault(productID);
        Console.WriteLine($"{temp.ProductID} {temp.ProductName} {temp.ProductQuantity} {temp.Price}");
    }
    public void delete(int productID)
    {
        Inventory.Remove(productID);
    }
}
public class InventoryManagementSystem
{
    public static void Main(string[] args)
    {
        Product product = new Product();
        product.ProductID = 1;
        product.ProductName = "Milk";
        product.ProductQuantity = 20;
        product.Price = 23;
        Product product2 = new Product();
        product2.ProductID = 2;
        product2.ProductName = "Water";
        product2.ProductQuantity = 100;
        product2.Price = 20;
        InventoryManagement inventoryManagement = new InventoryManagement();
        inventoryManagement.add(1, product);
        inventoryManagement.add(2, product2);
        inventoryManagement.update(2);
        inventoryManagement.update(1);
        inventoryManagement.delete(1);


    }
}

